### ISSUE TITLE
Bestanden opslaan crasht

### ISSUE THREAD

**Issue by nidunc** [mhoek2/pycalculator#8]
Dit lijkt nog niet helemaal goed te werken: https://github.com/mhoek2/pycalculator/blob/211e923c6e9ca96c1eae71460864034f7d3038b3/modules/notes.py#L31

Als ik tekst invoer op het Notities tabblad en op Opslaan klik, crasht het programma met de volgende foutmelding:
```
file: 'notes/note_19_09_2024-14_42_56.txt' is invalid!
create: 'notes/note_19_09_2024-14_42_56.txt' is invalid!
Traceback (most recent call last):
  File "c:\Users\Admin\Documents\GitHub\pycalculator\main.py", line 94, in <module>
    app.run()
  File "c:\Users\Admin\Documents\GitHub\pycalculator\main.py", line 77, in run
    self._handle_events()
  File "c:\Users\Admin\Documents\GitHub\pycalculator\main.py", line 72, in _handle_events
    self.m_gui.event_handler( event_list )
  File "c:\Users\Admin\Documents\GitHub\pycalculator\modules\gui\gui.py", line 195, in event_handler
    self.button_group_event_handler( event )
  File "c:\Users\Admin\Documents\GitHub\pycalculator\modules\gui\gui.py", line 185, in button_group_event_handler
    b.call_back()
  File "c:\Users\Admin\Documents\GitHub\pycalculator\modules\gui\button.py", line 48, in call_back
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\Documents\GitHub\pycalculator\modules\gui\gui.py", line 371, in saveNote
    self.m_context.m_notes.save( self.getNote() )
  File "c:\Users\Admin\Documents\GitHub\pycalculator\modules\notes.py", line 31, in save
    self.file = FileHandler( f"notes/{filename}.txt", True )
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\Documents\GitHub\pycalculator\modules\app\files.py", line 28, in __init__
    self.__handleFilename( )
  File "c:\Users\Admin\Documents\GitHub\pycalculator\modules\app\files.py", line 48, in __handleFilename
    file = open(self.full_path, 'w')
           ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'notes/note_19_09_2024-14_42_56.txt'```

**Comment by mhoek2** [comment]
@nidunc 
Bestaat de map notes wel in de root folder?
pycalculator\notes

**Comment by mhoek2** [comment]
Het lijkt er op dat de map notes is verwijderd van github toen ik de map heb leeg gemaakt met test notities in deze commit:
80cde2ea804ddf0c9224a9e1d82be0e53c7ac619

**Comment by nidunc** [comment]
> @nidunc Bestaat de map notes wel in de root folder? pycalculator\notes

Dat was inderdaad waar het probleem aan lag. Wellicht kan er nog een test worden toegevoegd om te kijken of de map bestaat (en om die eventueel aan te maken als dat nog niet zo is).
